### ISSUE TITLE
react-native sample App crashes when starting the SDK

### ISSUE THREAD

**Issue by konstajaa** [mistsys/mist-vble-ios-sdk#11]
When trying to start mist SDK on IOS react-native app, the app crashes immediately when startWithToken() is called.

```
 const MistSDK = NativeModules.RNMistsdk;
 const MistSDKEvents = new NativeEventEmitter(MistSDK);
  
 MistSDK.startWithToken(MIST_SDK_TOKEN);
```
  
Adding NSMotionUsageDescription key to info.plist seems to resolve this issue.

```
<key>NSMotionUsageDescription</key>
<string>This app requires access to motion data for enhanced location services.</string>
```

**Comment by vishwakarmar-JNPR** [comment]
Hi @konstajaa , its already mentioned in the sample app {https://github.com/mistsys/mist-vble-ios-sdk/blob/master/SampleApps/ReactNative/SampleBlueDotExperience/ios/SampleBlueDotExperience/Info.plist}

If you add the Motion permission it  will resolve the crash.

Please check the ReactNative Sample App info.plist and Wiki Info. it's mention as one of requirement.

**Comment by vishwakarmar-JNPR** [comment]
Hi @konstajaa please follow the latest react-native-mistsdk npm pkg.

https://www.npmjs.com/package/@mistsys/react-native-mistsdk
